project:
  type: book

book:
  title: "FA23-Quantile Regression"
  author: "Norah Jones"
  date: "10/7/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - Visual_Representations.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
