project:
  type: book
  output-dir: docs

book:
  title: "FA23-Quantile Regression"
  author: "Jorge Galdos, Noureldin Kamel, and Thomas Domas"
  date: "10/7/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - analysis.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    self-contained: true
    theme: cosmo
  pdf:
    documentclass: scrreprt
execute:
  echo: true
  warning: false
  message: false
  error: true

editor: visual
