# Analysis

```{r, echo=FALSE, include=FALSE}
# installing/loading the package:
# if(!require(installr)) {
#   install.packages("installr"); 
#   require(installr)
# } #load / install+load installr
# # using the package:
# updateR()

# install.packages('rmarkdown')
# install.packages("quantreg")
library("quantreg")
#library(sjPlot)
library(haven)
library(gridExtra)
library(tidyverse)
#library(equatiomatic)
#library(fastDummies)
#library(pscl)

#library(gsheet)
#library(brant)
#library(MASS)
#library(lmtest)
#library(reshape2)

#library(nnet)
#library(AER)
#library(boot)

#library(asaur)

```

## Visualization

```{r, 'Getting Data housing'}
df <- read.csv("TrainData.csv") |>
  na.omit() |>
  distinct()

suppressWarnings({

p1 <- df |> ggplot(aes(x = GrLivArea)) +
  geom_histogram(binwidth = 100) +
  theme_bw() +
  ylab(NULL) +
  xlab("Above Ground Area (sq. ft.)")

p2 <- df |> ggplot(aes(x = YearBuilt)) +
  geom_histogram(binwidth = 5) +
  theme_bw() +
  ylab(NULL) +
  xlab("Year Built")

p3 <- df |> ggplot(aes(x = HouseStyle)) +
  geom_histogram(stat="count") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab(NULL) +
  xlab("House Style")

p4 <- df |> ggplot(aes(x = SalePrice)) +
  geom_histogram(binwidth = 10000) +
  theme_bw() +
  ylab(NULL) +
  xlab("Sale Price ($)")

grid.arrange(p1, p2, p3, p4, nrow = 2)
                 
})
```

### Visualizing quantile regression vs OLS

```{r, 'Visualizing housing'}

df |> ggplot(aes(y = SalePrice, x = LotArea)) +
  geom_point(size = 0.9) +
  geom_smooth(method = lm, se = F, color = "black") +
  geom_text(aes(y = 400000, x = 150000, label = "OLS"), color="black") + 
  geom_quantile(quantiles=0.5, color="red") + 
  geom_text(aes(y = 470000, x = 90000, label = "50th quantile"), color="red") + 
  ylab("Sale price ($)") +
  xlab("Lot area (Square feet)") +
  theme_bw()


df |> ggplot(aes(y = SalePrice, x = GrLivArea)) +
  geom_point(size = 0.9) +
  stat_smooth(method = lm, color = "black") +
  geom_text(aes(x = 4150, y = 500000, label = "OLS"), color="black") + 
  geom_quantile(quantiles=0.25, color="red") + 
  geom_text(aes(x = 4000, y = 270000, label = "25th quantile"), color="red") + 
  geom_quantile(quantiles=0.5, color="blue") + 
  geom_text(aes(x = 4150, y = 400000, label = "50th"), color="blue") + 
  geom_quantile(quantiles=0.75, color="green") + 
  geom_text(aes(x = 4000, y = 600000, label = "75th quantile"), color="green") + 
  xlab("Sale price ($)") +
  ylab("Above ground area (Square feet)") +
  theme_bw()
```

## Model creation

### QR model

```{r 'QR model creation'}
qreg_model50 = rq(data=df, SalePrice ~ GrLivArea + LotArea + TotRmsAbvGrd + as.factor(LotShape) + as.factor(Foundation), tau=0.5)
summary(qreg_model50)
```

### OLS model

```{r 'OLS model creation'}
ols = lm(data=df, SalePrice ~ GrLivArea + LotArea + TotRmsAbvGrd + as.factor(LotShape) + as.factor(Foundation))
summary(ols)
```

## Model evaluation

### Mean absolute error

### Root mean squared error

### Variance of error

### Min/max error
