# Introduction

Quantile regression (QR), like any regression model, illustrates the relationship between a response variable and one or more predictor variables. QR differs from traditional regression models, such as ordinary least squares (OLS) regression, in that it estimates the conditional quantiles of a response variable, given the predictors' values, as opposed to the conditional mean in OLS regression.

Due to its formula illustrated later, QR has several advantages over OLS, including relaxed assumptions, efficiency in non-Gaussian scenarios, and a broader perspective compared to traditional models. Unlike OLS, QR does not assume the normality of the conditional response variable distribution and is robust to heteroskedasticity. Furthermore, by considering the entire conditional distribution, QR offers a comprehensive understanding of distributions with higher moments---i.e., those with non-zero skewness, kurtosis, or even greater moments which may be significant in extreme distributions such as in financial data--- enabling a detailed examination of their shape, asymmetry, and heavy-tailed characteristics. This makes QR a valuable tool for investigating extreme quantiles, which are of particular interest in fields such as epidemiology, and capturing the entire range of the distribution beyond the central tendency and variability, offering insights beyond traditional regression methods.

To illustrate the benefits of quantile regression, the methods section will explain the mathematical properties of quantile regression as well as show some sample graphs showing the way quantile regression acts when given different parameters. After showing the capabilities of quantile regression, the analysis section will show the real world benefits of quantile regression. To do this, a dataset containing different characteristics of houses along with their listed price will be used. The analysis section will show how significance can change when looking at different quantiles as well as how the beta estimates of the QR method can be shown.
